### ISSUE TITLE
<partial call paths> shouldn't be added to the flat view

### ISSUE THREAD

**Issue by jmellorcrummey** [laksono/hpcviewer.e4#108]
The database ufront:/home/johnmc/cilk.db contains a database from a student program for my class. When I look at it with any version of hpcviewer, I see in the flat view

```
<unknown module>
   <unknown file>
      "partial call paths>
          ...

```
`<partial call paths>` shouldn't be put into the flat view.

**Comment by laksono** [comment]
You're right, it appears in flat view (and its cost 51% of the total time! How is it possible?).
To fix this I need to modify the hpcprof code to generate the correct value of procedure feature. Currently the value of attribute `f` of `partial call paths` is 1 instead of 4:
```
    <Procedure i="3499" n="&lt;partial call paths&gt;" f="1" v="0"/>
```
Here is the meaning of attribute `f` as defined in hpcprof:
```
const int  TYPE_NORMAL_PROC  = 0;  // nothing special. Default value
const int  TYPE_PLACEHOLDER  = 1;  // the proc is just a a place holder
const int  TYPE_ROOT         = 2;  // the proc is a root tyoe, shown in a separate view in hpcviewer
const int  TYPE_ELIDED       = 3;  // the proc shouldn't be shown in hpcviewer at all
const int  TYPE_TOPDOWN_PLACEHOLDER  = 4;  // special place holder for top-down tree only.
...
  { PARTIAL_CALLPATH,      PARTIAL_CALLPATH  ,  TYPE_PLACEHOLDER    }
```
I need to change to `TYPE_TOPDOWN_PLACEHOLDER` instead of `TYPE_PLACEHOLDER`.
Should push the change in `develop` or other branch?

**Comment by jmellorcrummey** [comment]
submit a pull request to master
