### ISSUE TITLE
hpcviewer -V should print version string, and not bring up GUI

### ISSUE THREAD

**Issue by martyitz** [laksono/hpcviewer.e4#128]

**Comment by laksono** [comment]
I think it is impossible to execute a code **before** the splash screen since the later can be executed BEFORE launching the JVM (to be checked).

From the code at [eclipse.c](https://git.eclipse.org/c/equinox/rt.equinox.framework.git/tree/features/org.eclipse.equinox.executable.feature/library/eclipse.c): The splash screen is first displayed by Eclipse launcher (written in C) and then it launches the JVM.

**Comment by martyitz** [comment]
Can you put a change in the launcher in eclipse.c, or is it part of a library that you have to use as is?

	Thanks,
		Marty

**Comment by laksono** [comment]
`eclipse.c` is part of Eclipse code.
