### ISSUE TITLE
disable name string abbreviation in the statistics pane?

### ISSUE THREAD

**Issue by jmellorcrummey** [laksono/hpcviewer.e4#179]
I see the issue below with the 2022.1 release of hpcviewer. I haven't tried it with the develop branch. If the issue is already addressed in develop, my apologies!

See the figure below.  The names in the statistics pane have "..." as the rightmost character. The names in the call stack pane don't get this treatment. The call stack pane shows as much of the name as fits up to the right edge of the column.

As you see in the figure below, the "..." consumes 3 of the 18 or so characters shown in the column. I would rather have the name clipped at the boundary of the column than devoting the rightmost three characters to "...".

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/3926112/154394044-deecca0c-33a4-4385-a03c-57d2781e868b.png">

**Comment by laksono** [comment]
The statistic table uses NatTable, and this behavior is the default in NatTable. I think it's possible to remove the three dots by creating a special cell painter. I don't think it's difficult.

The call stack table uses SWT table so it doesn't have this issue. The reason the Statistic table uses NatTable is because it allows to resize the row's height based on the highest font size (see issue #60).

**Comment by jmellorcrummey** [comment]
Should we use NatTable for the Call stack pane as well so that text resizing applies to this pane as well?

**Comment by laksono** [comment]
Yes, it would be better if all tables are based from NatTable. 
For the statistic table is more urgent because if the font for the procedure column is smaller than the font for the percentage column, then the numbers are cropped (if using SWT table).

**Comment by jmellorcrummey** [comment]
I see. The font in the Call stack view does resize, but the resizing didn't cause problems. It is fine as is.

**Comment by laksono** [comment]
Solved in  commit 18b7817
