### ISSUE TITLE
hpcviewer error with CCT filter

### ISSUE THREAD

**Issue by jmellorcrummey** [laksono/hpcviewer.e4#187]
I created a filter for Intel GPUs. The filter suppresses nodes with "cl::sycl::detail*". I quit hpcviewer, which saves the filter for later use. 

I reopened the same database. I get two pop ups. 

First:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/3926112/159956918-96e25b2f-4187-41ca-9cb3-d3588b35d10f.png">

After clicking OK on the first, a second pop-up indicating an error appears:

<img width="688" alt="image" src="https://user-images.githubusercontent.com/3926112/159957145-84c7f89c-6228-469f-ace4-923bd59509b3.png">

The error file says the following:

```

(hpcviewer:67442): Gtk-WARNING **: 15:49:27.385: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scroll
edwindow, owner GtkScrolledWindow)

(hpcviewer:67442): Gtk-WARNING **: 15:49:29.069: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scroll
edwindow, owner GtkScrolledWindow)

** (hpcviewer:67442): CRITICAL **: 15:49:29.249: JNI class pointer is NULL for class org/eclipse/swt/accessibility/AccessibleObject

** (hpcviewer:67442): CRITICAL **: 15:49:29.249: JNI class pointer is NULL for class org/eclipse/swt/accessibility/AccessibleObject
```

If I close that pop up, I can then open the same database properly from the file menu. It still gives the first pop up, but the error disappears.

I can provide a database on JLSE. You can add the filter and see the problem.

I would like to see two changes.
1. It is fine to flash the warning about CCT nodes elided, but it should be a pop-up that disappears without an active click. (enhancement request)
2. the error should not happen (bug report)

**Comment by laksono** [comment]
- Sometimes I saw the second error message "no active window" if I use TWM. It never happens when using Mac, and very rare when using GNOME WM.

- The error message in `hpcviewer.err` is different. It's due to Eclipse's issue on GTK. I saw in Eclipse platform mailing list, this only happens with some older GTK and doesn't happen with the latest GTK.

- Concerning the warning text, we can perhaps display it a message on top of the table so that we don't need to click the Ok button.

**Comment by laksono** [comment]
The fix is by adding an option whether the user wants to disable the warning window or not.
If the user doesn't want the warning window, no more window appears. Instead, the viewer shows the message on the table (and the user doesn't need to click any button)

![image](https://user-images.githubusercontent.com/8781032/172246881-954e33e8-18c3-4d9f-851d-c48563ba079b.png)
